<?php

namespace Ctc\AppBundle\Entity\Common;

//use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationRepository extends NestedTreeRepository
{

    


    public function findAllQuery(){
       $q = $this->getEntityManager()->createQuery('Select d from CtcAppBundle:Common\Destination d order by d.root, d.lft asc');

        return $this->getWithTranslation($q);


    }

    public function getWithTranslation($query){

        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        return $query;

    }

}
