parameters:
#    ctc_user.example.class: Ctc\UserBundle\Example

services:
#    ctc_user.example:
#        class: %ctc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
