parameters:
    knp.doctrine_behaviors.blameable_listener.user_entity: Ctc\UserBundle\Entity\User

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }
framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [MopaBootstrapBundle, CtcAppBundle]
    java: /usr/bin/java
#    sass: /usr/local/bin/sass
    filters:
        cssrewrite: ~
        sass:
            bin: /usr/local/bin/sass
        compass:
            bin: /usr/local/bin/compass
            apply_to: "\.scss$"
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ctc\UserBundle\Entity\User

mopa_bootstrap:
    navbar: ~

    form:
#        templating: false
        show_legend: false # default is true
        show_child_legend: false # default is true

stof_doctrine_extensions:
    default_locale: en_US #%locale%
    translation_fallback: true
    orm:
        default:
            translatable: true
            tree: true
            sluggable: true
            timestampable: true
            blameable: true
            sortable: true

a2lix_translation_form:
    locales: [es, en]       # [1]
    default_required: true      # [2]
    templating: "A2lixTranslationFormBundle::default.html.twig"      # [3]
    use_aop: false              # [4]
    default_class:
        service: "A2lix\TranslationFormBundle\TranslationForm\DefaultTranslationForm"
        listener: "A2lix\TranslationFormBundle\Form\EventListener\DefaultTranslationsSubscriber"
        types:
             translations: "A2lix\TranslationFormBundle\Form\Type\TranslationsType"
             translationsFields: "A2lix\TranslationFormBundle\Form\Type\TranslationsFieldsType"