<?php

namespace Ctc\AppBundle\Entity\Hotel;

use Doctrine\ORM\EntityRepository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends EntityRepository
{

    public function findAllQuery(){
        $q = $this->getEntityManager()->createQuery('Select d, t from CtcAppBundle:Hotel\Hotel d left join d.translations t');

        return $q;


    }


    public function findAll(){

        return $this->findAllQuery()->execute();

    }

}
